# Language analysis


## Top languages

Top languages according to title count in each “national” context 


```{r top_language, echo=FALSE, message=FALSE, warning=FALSE, out.width="25%"}
# Combine language data from catalogs
df <- NULL
for (ctl in names(catalogs)) {
  tmp <- catalogs[[ctl]][, c("language_primary", "publication_country")]
  tmp$catalog <- rep(ctl, nrow(tmp))
  df <- dplyr::bind_rows(df, tmp)
}

# For each country, show top languagues
ntop <- 5
for (country in unique(df$publication_country)) {

  dfs <- subset(df, publication_country == country)
  ctl <- paste(unique(dfs$catalog), collapse = "+")
  library(comhis)
  library(ggplot2)  
  p <- top_plot(dfs$language_primary, ntop = ntop) +
       labs(title = country, subtitle = ctl) +       
       scale_y_log10() +
       theme_comhis("discrete", base_size=25)
       
  print(p)

}
```



## Top languages by town

Top languages by town (based on the indicated catalog).

```{r top_language_by_town, echo=FALSE, message=FALSE, warning=FALSE, out.width="33%", fig.width=10, fig.height=7}
# Combine language data from catalogs
df <- NULL
# Exclude STCN as it does not have towns
df <- NULL
for (ctl in setdiff(names(catalogs), "stcn")) {
  tmp <- catalogs[[ctl]][, c("language_primary", "publication_country", "publication_place")]
  tmp$catalog <- rep(ctl, nrow(tmp))
  df <- dplyr::bind_rows(df, tmp)
}


selected.towns <- as.data.frame(rbind(
  c("London", "estc"),
  c("Oxford", "estc"),
  c("Cambridge", "estc"),
  #c("Leiden", "hpb"),
  #c("Amsterdam", "hpb"),
  #c("Vienna", "hpb"),
  #c("Salzburg", "hpb"),
  #c("Tallinn", "hpb"),
  #c("Tartu", "hpb"),
  c("Stockholm", "snb"),
  c("Lund", "snb"),
  c("Uppsala", "snb"),
  c("Turku", "fnb")))
names(selected.towns) <- c("town", "catalog")

# For each country, show top languagues
ntop <- 5
for (i in seq_len(nrow(selected.towns))) {
  ctl <- selected.towns[i, "catalog"]
  town <- selected.towns[i, "town"]

  # Pick the selected town and catalog
  dfs <- subset(df, publication_place == town & catalog == ctl)
  
  library(comhis)
  library(ggplot2)  
  p <- top_plot(dfs$language_primary, ntop = ntop) +
       labs(title = town, subtitle = ctl) +
       scale_y_log10() +
       theme_comhis("discrete", base_size=30)
       
  print(p)

}
```
