# Genre analysis

```{r setup, include=FALSE}
# Global options
# library(knitr)
# opts_chunk$set(fig.path="/")
```

Top genres illustrated.

Here we show the ones with the highest standard deviation over time.

```{r diverse_genre, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=6}
df0 <- df <- catalogs[["stcn"]]

# Most common genres out of all separate ones
spl <- stringr::str_split(df$genre, "\\|")
top.genres <- names(which(rev(sort(table(unlist(spl)))) > 500))[1:10]

# List all year-genre pair occurrences, calculate their frequencies, and make a wide table

# Gatherings with N>400
dfglist <- list()
top.gatherings <- names(which(sort(table(df0$gatherings)) > 400))
for (gat in top.gatherings) {

  df <- df0 %>% filter(gatherings == gat)
  spl <- stringr::str_split(df$genre, "\\|")

  dfg <- data.frame(publication_year = unlist(sapply(seq(nrow(df)),
         function (i) {rep(df$publication_year[[i]], length(spl[[i]]))})), genre = unlist(spl)) %>%
	 group_by(publication_year, genre) %>%
	 tally() %>%
	 select(publication_year, genre, n) %>%
         tidyr::pivot_wider(names_from = publication_year, values_from = n, values_fill=0)

  dfglist[[gat]] <- dfg

}
```




For a given genre, quantify variability from Latin to Vernacular language.

```{r diverse_genre2, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=6}
library(stringr)
taulist <- list()

for (sel.gat in top.gatherings) {

  tau <- c()
  pics <- list()
  dfw <- df0 %>% filter(gatherings == gat)
  spl <- stringr::str_split(dfw$genre, "\\|")

  for (sel.genre in top.genres) {

    dfw$hit <- sapply(spl, function (x){sel.genre %in% x})
    dfl <- dfw %>% filter(hit) %>%
               filter(language_primary %in% c("Latin", "Dutch")) %>%
       	       group_by(publication_year, language_primary) %>%	       
	       tally() %>%
	       select(publication_year, language_primary, n) %>%
               tidyr::pivot_wider(names_from = language_primary, values_from = n, values_fill=0)

     if (!"Latin" %in% names(dfl)) {
       dfl$Latin <- rep(0, nrow(dfl))
     }
     if (!"Dutch" %in% names(dfl)) {
       dfl$Dutch <- rep(0, nrow(dfl))
     }

     dfl <- dfl %>%
	       mutate(Both = Latin + Dutch) %>%
	       mutate(Vernacular_Freq = Dutch / Both)

    # Measure time correlation with Kendall's tau
    tau[[sel.genre]] <- unname(cor.test(dfl$Vernacular_Freq, dfl$publication_year, method = "kendall")$estimate)

  }

  taulist[[sel.gat]] <- tau

}


dfs0 <- df0 %>% filter(gatherings %in% top.gatherings) %>%
                group_by(publication_decade, gatherings, genre) %>%
                summarise(n=n()) %>%
		mutate(f=n/sum(n)) %>%
		mutate(genre=droplevels(factor(genre)))


for (sel.gat in top.gatherings) {

  # Pick genres that shift most from Latin to Vernacular as quantified by tau
  most.variable.genres <- names(rev(sort(unlist(taulist[[sel.gat]])))[1:5])
  dfs <- dfs0 %>% filter(genre %in% most.variable.genres) %>%
                  filter(gatherings %in% sel.gat) 

  p <- ggplot(dfs, aes(x = publication_decade, color=genre, fill=genre, y = f)) +
       geom_line() +
       geom_point() +       
       labs(title="Top variable genres", subtitle=paste(sel.gat)) +
       theme_comhis("discrete", base_size=20) +
       labs(x = "Publication decade", y = "Genre share (%)", fill="Genre") +
       scale_y_continuous(label=scales::percent)
       
  print(p)

}
```







For each document type, quantify top genres over time. 

```{r doctypes, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=6}
for (doctype in na.omit(as.character(unique(df0$document_type)))) {

  dfw <- df0 %>% filter(document_type == doctype)
  spl <- stringr::str_split(dfw$genre, "\\|")

  dflong <- NULL
  
  for (sel.genre in top.genres) {

    dfw$hit <- sapply(spl, function (x){sel.genre %in% x})
    
    dfl <- dfw %>% filter(hit) %>%
               filter(language_primary %in% c("Latin", "Dutch")) %>%
       	       group_by(publication_year, language_primary) %>%	       
	       tally() %>%
	       select(publication_year, language_primary, n) %>%
               tidyr::pivot_wider(names_from = language_primary, values_from = n, values_fill=0)
    
     dfl$genre <- rep(sel.genre, rep = nrow(dfl))

     if (!"Latin" %in% names(dfl)) {
       dfl$Latin <- rep(0, nrow(dfl))
     }
     if (!"Dutch" %in% names(dfl)) {
       dfl$Dutch <- rep(0, nrow(dfl))
     }

     dfl <- dfl %>%
	       mutate(Both = Latin + Dutch) %>%
	       mutate(Vernacular_Freq = Dutch / Both)

     dflong <- bind_rows(dflong, dfl)

  }

  dflong$genre <- factor(dflong$genre)
  p <- ggplot(dflong, aes(x = publication_year, color=genre, fill=genre, y = Vernacular_Freq)) +
       geom_smooth()  +
       geom_point() +       
       labs(title="Top genres: vernacular frequency", subtitle=paste(doctype)) +
       theme_comhis("discrete", base_size=20) +
       labs(x = "Publication year", y = "Vernacular frequency (%)", color="Genre", fill="Genre") +
       scale_y_continuous(label=scales::percent)
       
  print(p)

}
```



Same with all document types combined.


```{r doctypescombined, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=6}

  dfw <- df0
  spl <- stringr::str_split(dfw$genre, "\\|")

  dflong <- NULL
  
  for (sel.genre in top.genres) {

    dfw$hit <- sapply(spl, function (x){sel.genre %in% x})
    
    dfl <- dfw %>% filter(hit) %>%
               filter(language_primary %in% c("Latin", "Dutch")) %>%
       	       group_by(publication_year, language_primary) %>%	       
	       tally() %>%
	       select(publication_year, language_primary, n) %>%
               tidyr::pivot_wider(names_from = language_primary, values_from = n, values_fill=0)
    
     dfl$genre <- rep(sel.genre, rep = nrow(dfl))

     if (!"Latin" %in% names(dfl)) {
       dfl$Latin <- rep(0, nrow(dfl))
     }
     if (!"Dutch" %in% names(dfl)) {
       dfl$Dutch <- rep(0, nrow(dfl))
     }

     dfl <- dfl %>%
	       mutate(Both = Latin + Dutch) %>%
	       mutate(Vernacular_Freq = Dutch / Both)

     dflong <- bind_rows(dflong, dfl)

  }

  dflong$genre <- factor(dflong$genre)
  p <- ggplot(dflong, aes(x = publication_year, color=genre, fill=genre, y = Vernacular_Freq)) +
       geom_smooth()  +
       geom_point() +       
       labs(title="Top genres: vernacular frequency", subtitle="all documents") +
       theme_comhis("discrete", base_size=20) +
       labs(x = "Publication year", y = "Vernacular frequency (%)", color="Genre", fill="Genre") +
       scale_y_continuous(label=scales::percent)
       
  print(p)


```




