# Publication place analysis


## Top places

Top towns according to title count in each “national” context.

```{r top_place, echo=FALSE, message=FALSE, warning=FALSE, out.width="33%"}
# Combine place data from catalogs
# Exclude STCN as it does not have towns
library(comhis)
library(ggplot2)  

df <- NULL
for (ctl in names(catalogs)) {
  tmp <- data.frame(publication_country=catalogs[[ctl]][, c("publication_country")])
  tmp$catalog <- rep(ctl, nrow(tmp))
  df <- dplyr::bind_rows(df, tmp)
}

# For each country, show top towns
ntop <- 5

for (cata in unique(df$catalog)) {

  dfs <- subset(df, catalog == cata)
  dfs$publication_country <- compress_field(dfs$publication_country, topn=ntop)

  print(toupper(cata))
  dftab <- dfs %>% group_by(publication_country) %>% tally()
  print(knitr::kable(dftab))

  p <- top_plot(dfs$publication_country, ntop = ntop+1, show.percentage=TRUE) +
       labs(title = toupper(cata)) +
       scale_y_log10() +
       theme_comhis("discrete", base_size=25)
       
  print(p)

}
```





## Countries per catalog

Summary of selected countries per catalog, for quality control purposes. Should have the same countries than above.

```{r countries, echo=FALSE, message=FALSE, warning=FALSE}
for (catal in names(catalogs)) {
  print(catal)
  tab <- table(catalogs[[catal]]$publication_country)
  print(tab[tab > 0])
  print("----------")
}
```