# STCN analyses

```{r setup, include=FALSE}
# Global options
# library(knitr)
# opts_chunk$set(fig.path="/")
```



### STCN languages over time

```{r lang, out.width="80%", fig.width=10, fig.height=5, echo=FALSE, warning=FALSE, message=FALSE}
df <- catalogs$stcn %>%
        filter(publication_decade < 1800) %>%
        group_by(publication_decade, language_primary) %>%
	summarize(n=n())

# Keep top lang and put rest in other category

df$language_primary <- compress_field(df$language_primary, topn = 3, rest = "Other")

#cols <- c("red", "blue", "pink", "magenta")
p <- ggplot(df, aes(x=publication_decade, color=language_primary, y=n)) +
       #geom_bar(stat="identity") +
       geom_line() +
       geom_point() +
       #geom_smooth() + 
       labs(x = "Publication decade",
            y = "Title count (n)",
            color = "Primary language") +
            #fill  = "Primary language") +
       #scale_color_manual(values = cols) +
       #scale_fill_manual(values = cols) +        
       theme_comhis("continuous", 30)

print(p)
```
